server:
  port: 7003

eureka:
  server:
    enable-self-preservation: false        #禁用保护,上线时改为true
    eviction-interval-timer-in-ms: 10000    #清理间隔（默认是60*1000）
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/

spring:
  application:
    name: provider-redis7003
  redis: # Redis
    database: 0
    host: 120.77.240.238 #远程服务器redis
    port: 6379 #redis端口号
    #password: lv85208520 #redis密码
    #timeout: 6000
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 5
        min-idle: 3

